apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: haproxy-k8s-external-lb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: haproxy-k8s-external-lb
subjects:
- kind: ServiceAccount
  name: haproxy-k8s-external-lb
  namespace: default